### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by abvadabra** [hexosse/WorldEditCUI-Forge-Edition#1]
Are you going to release the source code to the public? If not, what is the purpose of this repo?

**Comment by lahwran** [comment]
Yeah, it'd be pretty cool to do that.

**Comment by hexosse** [comment]
Hello,

This repository on GitHub is only used to store the update.json file used by forge to prevent the user in case of update.
However, if you need some kind of help I'll be glade to help you.
