### ISSUE TITLE
Publish the code. 

### ISSUE THREAD

**Issue by lahwran** [hexosse/WorldEditCUI-Forge-Edition#2]
You are using code taken from a community, from a lineage starting with a gl example by ultramoogleman, then a mod by me, and later others. You don't get to decide you're the last step in the chain. Publish it.

**Comment by wizjany** [comment]
@hexosse I'd like to note that you're using code that was released under the EPL, which means that even if you write new (e.g. forge-specific) code, you are still bound by the original terms of the license. https://www.eclipse.org/legal/eplfaq.php#MODDIST

As in issue #1 you can't just decide to not publish the code because you don't want to.
I'd also like to add that you added a request for donations in your README file shortly after closing that issue, which is a pretty scummy thing to do given the circumstances.

**Comment by hexosse** [comment]
As I mentionned in the readme, this mod was originally written by lahwran then yetanotherx and Mumfrey.
Both of them have a public repo on github, so the rendering code is still present on the web:

lahwran/worldeditcui : https://github.com/lahwran/worldeditcui
yetanotherx/WorldEditCUI : https://github.com/yetanotherx/WorldEditCUI
Mumfrey/WorldEditCUI : https://github.com/Mumfrey/WorldEditCUI

So every one who want to reuse the rendering part of the code as I did can have a look to thoses repos.

However, I just published the code which is under EPL that I reused from the original authors.

**Comment by lahwran** [comment]
Yeah, the key is that publishing changes is required too.

**Comment by lahwran** [comment]
Thanks! :)

**Comment by Polyana-Fontes** [comment]
@lahwran @Mumfrey  Does EPL allows to publish obfuscated updates without the updated source code?
![image](https://cloud.githubusercontent.com/assets/3679022/20343685/2906c526-abce-11e6-85c7-04791830cc92.png)

**Comment by lahwran** [comment]
I am not a lawyer, but my understanding is that it requires sharing of the source of any derivative works, which I'm pretty sure this is. Separate modules would be allowed, so if HexoMod were to write extensions that were closed source and edit the open source portion to interact with them, that'd be allowed; however, the open source portion is definitely copyleft, and may not be published compiled without also being published as source.

**Comment by wizjany** [comment]
Yup, that's part of the OSD. Derivatives of the original source must remain open.

Out of curiosity @hexosse why do you want to keep this so closed? Do you have some issue with releasing the source?

**Comment by hexosse** [comment]
I'm not a lawyer too, so I just read again the [Eclipse Public License (EPL) Frequently Asked Questions](https://www.eclipse.org/legal/eplfaq.php#PROPPROD) and they state :

> 1. **What is required for OSI license approval?**
>    A license qualifies for OSI approval if it conforms to the OSI’s "Open Source Definition" or "OSD." The OSD covers nine topics of concern. Chief among these is the requirement that a license not restrict any party from selling or giving away the software. Further, the Program must include source code, must allow distribution in source code as well as compiled form, and must allow modifications and derived works. Find more information on the OSD at opensource.org.

So I'll include the source code in the next release.

@wizjany there's only a few part of the code that I want to keep, but it was easier to obfuscate everything.
However, if someone wants a full example on how to overlay blocks or whatever (chest, entities, ...) I can make a full working sample.
