### ISSUE TITLE
Comply with WorldEditCUI license

### ISSUE THREAD

**Issue by bendoerr** [hexosse/WorldEditCUI-Forge-Edition#6]
First, I'm very grateful that you've modified @lahwran's @yetanotherx's @Mumfrey's WorldEditCUI to be supported by Forge. I always felt adding Liteloader just for this one mod was a waste in my use case. 

Their code as other have said is licensed under the EPL which has a copyleft clause requiring the source of derivatives to be published as well. It appears that you have published the original but not your derivative. @lahwran opened issue #2 requesting that you comply with the licensing which you just closed without complying.

**Comment by hexosse** [comment]
Project discontinued
