### ISSUE TITLE
Doesn't work with WorldEdit also installed clientside

### ISSUE THREAD

**Issue by boy0001** [hexosse/WorldEditCUI-Forge-Edition#7]
Something about registering the same messaging channel. You don't post the source so I can't see. 

https://hastebin.com/azidudubic.css

**Comment by hexosse** [comment]
Tell me a bit more about which version of WorldEdit and WorldEditCUI ?

**Comment by boy0001** [comment]
It does it with multiple versions, though this specific one was `worldedit-6.1.6-SNAPSHOT;3650-a339a79` and `wecuife-1.0.5`. 

Also, the error only seems to happen when the WorldEditCUI or WorldEdit jars are renamed. Above I had `WorldEdit.jar` and `WorldEdit-CUI.jar`. I think your code might be looking for files named `worldedit` and `worldeditcui`, and breaks something if they don't exist.

**Comment by hexosse** [comment]
This was due to WorldEditCui loading before WorldEdit.
I changed the dependency in 1.0.6, so everything should work fine now.
