### ISSUE TITLE
Cyl/Sphere/Ellipsoid selections do not render properly

### ISSUE THREAD

**Issue by jjyyxx** [hexosse/WorldEditCUI-Forge-Edition#8]
Running Minecraft 1.11.2 and WorldEdit 6.1.6 on Forge 13.20.0.2228, only poly and normal cuboid regions render properly.

Cylinders, spheres, and ellipsoids render as a cuboid, and not as as cylinder, sphere, or ellipsoid.

**Comment by hexosse** [comment]
This happens when using WorldEdit for **forge**, which doesn't send the correct information.
It only works when using the Bukkit version.

**Comment by jjyyxx** [comment]
Are there any other solutions apart from installing a Liteloader version of CUI(I'm tired of installing  Liteloader)?

**Comment by hexosse** [comment]
Not for the moment.
I might look into WE code to submit a PR as lots of people have this problem.

As you are on mc 1.11.2, consider using [WorldEditCUI Forge Edition 2
](https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2) which have much more features
